"""Global (forward) world-model adapters for the local/global track.

Two implementations behind one small interface:

- :class:`SyntheticPointGlobalModel` — exact dynamics for the synthetic
  point-mass task generated by ``datasets.generate_synthetic_task``. Used by
  CPU smoke runs and tests; it is a *perfect* global model by construction.
- :class:`DinoWMGlobalModel` — loads a DINO-WM checkpoint in-process from the
  upstream checkout (requires the upstream repo and its dependencies; intended
  for Colab). The latent-bypass patch installed by
  ``scripts/dino_wm/patch_latent_cache.py`` lets ``encode_obs`` consume cached
  patch latents directly, so rollouts stay in latent space end to end.

Upstream rollout contract (``VWorldModel.rollout(obs_0, act)``): with ``n``
context frames, ``act`` must hold one folded action block per context frame
followed by the future blocks — ``act[:, :n]`` is attached to the context
window and ``L`` total blocks simulate ``L - n + 1`` model steps. The adapter
therefore keeps the *original* observed context plus every executed block and
replays from there each call, which also keeps proprio conditioning honest
(proprio is only ever the truly observed one). Checkpoints trained with
upstream ``normalize_action: true`` consumed normalized actions/proprio, so
the adapter normalizes at its boundary; planners and the local surrogate keep
working in raw units.

All global-model calls run under ``torch.no_grad()`` — gradients only ever
come from the local surrogate.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Protocol

import numpy as np

try:
    import torch
except ImportError as exc:  # pragma: no cover
    raise RuntimeError("PyTorch is required to use local_global.global_models.") from exc

from wm_poc.local_global.datasets import (
    SYNTHETIC_DAMPING,
    SYNTHETIC_DT,
    SYNTHETIC_DYNAMICS_NAME,
)


class GlobalModel(Protocol):
    """Forward simulator over global latents (never differentiated)."""

    frameskip: int
    context_len: int

    def init_state(
        self,
        z_context: torch.Tensor,
        proprio_context: torch.Tensor | None = None,
        actions_context: torch.Tensor | None = None,
    ) -> dict[str, Any]: ...

    def rollout_final(self, state: dict[str, Any], actions: torch.Tensor) -> torch.Tensor: ...

    def advance(self, state: dict[str, Any], actions: torch.Tensor) -> dict[str, Any]: ...

    def current_latent(self, state: dict[str, Any]) -> torch.Tensor: ...


def latent_goal_cost(z_pred: torch.Tensor, z_goal: torch.Tensor) -> torch.Tensor:
    """Mean squared latent distance per batch element: ``(B, P, D), (P, D) -> (B,)``."""
    diff = z_pred - z_goal.to(z_pred.device, z_pred.dtype)
    return torch.mean(diff**2, dim=tuple(range(1, diff.ndim)))


class SyntheticPointGlobalModel:
    """Exact global model for the synthetic linear-latent point-mass task."""

    def __init__(self, action_dir: str | Path, *, frameskip: int = 1, device: str = "cpu") -> None:
        action_dir = Path(action_dir).expanduser()
        dynamics_path = action_dir / SYNTHETIC_DYNAMICS_NAME
        if not dynamics_path.is_file():
            raise FileNotFoundError(f"Not a synthetic task dir (missing {dynamics_path}).")
        with dynamics_path.open("r", encoding="utf-8") as f:
            self.dynamics: dict[str, Any] = json.load(f)
        weight = np.load(action_dir / "encoder_weight.npy")  # (P*D, S)
        bias = np.load(action_dir / "encoder_bias.npy")  # (P*D,)
        # Co-locate the encode/decode buffers with the planner's device: CEM
        # candidates arrive on that device, so CPU-pinned buffers would raise a
        # cross-device error in _step_raw (e.g. on an A100 with device=cuda).
        self.device = torch.device(device)
        self.weight = torch.from_numpy(weight).float().to(self.device)
        self.bias = torch.from_numpy(bias).float().to(self.device)
        self.pinv = torch.linalg.pinv(self.weight)  # (S, P*D), on self.device
        self.patches = int(self.dynamics["patches"])
        self.embed_dim = int(self.dynamics["embed_dim"])
        self.action_dim = int(self.dynamics["action_dim"])
        # The cached data is self-describing; never assume module constants match.
        self.dt = float(self.dynamics.get("dt", SYNTHETIC_DT))
        self.damping = float(self.dynamics.get("damping", SYNTHETIC_DAMPING))
        self.frameskip = int(frameskip)
        self.context_len = 1

    def decode_state(self, z: torch.Tensor) -> torch.Tensor:
        flat = z.float().to(self.device).reshape(*z.shape[:-2], self.patches * self.embed_dim)
        return (flat - self.bias) @ self.pinv.T

    def encode_state(self, state: torch.Tensor) -> torch.Tensor:
        flat = state.float().to(self.device) @ self.weight.T + self.bias
        return flat.reshape(*state.shape[:-1], self.patches, self.embed_dim)

    def _step_raw(self, state: torch.Tensor, action: torch.Tensor) -> torch.Tensor:
        pos, vel = state[..., :2], state[..., 2:]
        new_vel = self.damping * vel + self.dt * action
        new_pos = torch.clamp(pos + self.dt * new_vel, -1.0, 1.0)
        return torch.cat([new_pos, new_vel], dim=-1)

    def init_state(
        self,
        z_context: torch.Tensor,
        proprio_context: torch.Tensor | None = None,
        actions_context: torch.Tensor | None = None,
    ) -> dict[str, Any]:
        with torch.no_grad():
            return {"state": self.decode_state(z_context[-1])}

    def _unfold(self, actions: torch.Tensor) -> torch.Tensor:
        lead = actions.shape[:-2]
        steps = actions.shape[-2]
        return actions.reshape(*lead, steps * self.frameskip, self.action_dim)

    def rollout_final(self, state: dict[str, Any], actions: torch.Tensor) -> torch.Tensor:
        """Batched open-loop rollout: actions ``(B, K, fs*A)`` -> final latents ``(B, P, D)``."""
        with torch.no_grad():
            raw = self._unfold(actions.float().to(self.device))
            current = state["state"].unsqueeze(0).expand(raw.shape[0], -1).clone()
            for t in range(raw.shape[1]):
                current = self._step_raw(current, raw[:, t])
            return self.encode_state(current)

    def advance(self, state: dict[str, Any], actions: torch.Tensor) -> dict[str, Any]:
        """Commit executed blocks ``(m, fs*A)``; per-model-step latents in ``step_latents``."""
        with torch.no_grad():
            blocks = actions.float().to(self.device)
            current = state["state"].clone()
            step_latents = []
            for b in range(blocks.shape[0]):
                raw = blocks[b].reshape(self.frameskip, self.action_dim)
                for t in range(self.frameskip):
                    current = self._step_raw(current, raw[t])
                step_latents.append(self.encode_state(current))
            return {"state": current, "step_latents": torch.stack(step_latents, dim=0)}

    def current_latent(self, state: dict[str, Any]) -> torch.Tensor:
        with torch.no_grad():
            return self.encode_state(state["state"])


def _find_in_cfg(node: Any, key: str) -> Any:
    """Depth-first search for a key in a nested (OmegaConf-derived) mapping."""
    if isinstance(node, dict):
        if key in node:
            return node[key]
        for value in node.values():
            found = _find_in_cfg(value, key)
            if found is not None:
                return found
    elif isinstance(node, list):
        for value in node:
            found = _find_in_cfg(value, key)
            if found is not None:
                return found
    return None


class DinoWMGlobalModel:
    """In-process DINO-WM world model driven on cached latents.

    Loads the upstream checkpoint exactly like ``plan.py`` does: from
    ``<ckpt_base_path>/outputs/<model_name>/hydra.yaml`` plus
    ``checkpoints/model_<epoch>.pth``. Requires the upstream repo (with the
    wm_poc latent-bypass patch applied) importable and its dependencies
    installed — i.e. the Colab runtime, not the local test environment.

    The rollout state keeps the original observed context (latents + raw
    proprio + the n-1 folded action blocks that produced it) and the list of
    executed blocks; every call replays from that anchor, so the upstream act
    contract (one block per context frame, then future blocks) is satisfied
    and the model is never conditioned on stale or fabricated proprio.
    """

    def __init__(
        self,
        repo_path: str | Path,
        run_output_dir: str | Path,
        *,
        model_epoch: str = "latest",
        device: str = "cuda",
        latent_dim: int = 384,
        frameskip: int = 5,
        num_hist: int = 3,
        rollout_batch_size: int = 64,
        action_stats: dict[str, np.ndarray] | None = None,
        wm: Any = None,
    ) -> None:
        self.repo_path = Path(repo_path).expanduser()
        self.run_output_dir = Path(run_output_dir).expanduser()
        self.device = torch.device(device)
        self.latent_dim = int(latent_dim)
        self.frameskip = int(frameskip)
        self.context_len = int(num_hist)
        # CEM populations are scored in chunks of this size so the same
        # experiment fits any GPU: results are identical (candidates are
        # independent), only wall-clock changes. Tune per card via
        # global_model.rollout_batch_size (e.g. 128 on A100, 32 on T4).
        self.rollout_batch_size = max(1, int(rollout_batch_size))
        self._calls = 0
        self.normalize = True
        if wm is not None:  # test injection: skip the upstream load entirely
            self.wm = wm
        else:
            self.wm = self._load_upstream(model_epoch)
        self._init_stats(action_stats)

    def _load_upstream(self, model_epoch: str) -> Any:
        if not (self.repo_path / "plan.py").is_file():
            raise FileNotFoundError(
                f"Upstream dino_wm repo not found at {self.repo_path} (no plan.py)."
            )
        hydra_cfg = self.run_output_dir / "hydra.yaml"
        ckpt = self.run_output_dir / "checkpoints" / f"model_{model_epoch}.pth"
        if not hydra_cfg.is_file() or not ckpt.is_file():
            raise FileNotFoundError(
                f"Expected {hydra_cfg} and {ckpt}; pass the run output dir that "
                "upstream training produced (outputs/<run_name>)."
            )
        if str(self.repo_path) not in sys.path:
            sys.path.insert(0, str(self.repo_path))
        from omegaconf import OmegaConf  # provided by the upstream environment

        train_cfg = OmegaConf.load(hydra_cfg)
        container = OmegaConf.to_container(train_cfg, resolve=False)
        normalize = _find_in_cfg(container, "normalize_action")
        self.normalize = True if normalize is None else bool(normalize)
        try:
            from plan import load_model  # upstream helper used by plan.py itself
        except ImportError as exc:
            raise RuntimeError(
                "Could not import load_model from the upstream plan.py; verify the "
                "dino_wm checkout and its dependencies (hydra, omegaconf, torch)."
            ) from exc
        num_action_repeat = _find_in_cfg(container, "num_action_repeat") or 1
        wm = load_model(ckpt, train_cfg, num_action_repeat, device=self.device)
        # Upstream load_model places most of the model on `device`, but a
        # submodule (e.g. a hub-loaded DINOv2 encoder, or checkpoint modules
        # loaded to CPU) can stay off it, surfacing as "cuda:0 and cpu" in
        # F.linear during rollout. Force the whole module -- params + buffers --
        # onto the target device; a top-level .to() recurses into every current
        # submodule, so it catches anything upstream's internal move missed.
        try:
            wm = wm.to(self.device)
        except Exception as exc:  # pragma: no cover - depends on upstream shape
            print(f"[dino_wm] warning: wm.to({self.device}) failed: {exc}")
        wm.eval()
        # Flag only genuine mismatches: a param on "cuda:0" matches a requested
        # "cuda" (type cuda, unspecified index), so compare by type and -- when
        # the target pins an index -- by index, not by the raw device string.
        target = self.device
        misplaced = sorted(
            {
                str(p.device)
                for p in wm.parameters()
                if p.device.type != target.type
                or (target.index is not None and p.device.index != target.index)
            }
        )
        if misplaced:
            # A stray plain-tensor attribute (not a registered param/buffer)
            # cannot be reached by .to(); surface it rather than failing deep in
            # the rollout with an opaque device error.
            print(
                f"[dino_wm] warning: model parameters still span {misplaced} "
                f"after moving to {self.device}; rollouts may hit a device mismatch. "
                "This points to a non-registered tensor attribute in the upstream model."
            )
        return wm

    def _init_stats(self, action_stats: dict[str, np.ndarray] | None) -> None:
        def tensor(key: str) -> torch.Tensor | None:
            if action_stats is None or key not in action_stats:
                return None
            return torch.from_numpy(np.asarray(action_stats[key], dtype=np.float32)).to(
                self.device
            )

        self.action_mean = tensor("action_mean")
        self.action_std = tensor("action_std")
        self.state_mean = tensor("state_mean")
        self.state_std = tensor("state_std")
        if self.normalize and (self.action_mean is None or self.action_std is None):
            raise ValueError(
                "This checkpoint was trained with normalize_action=true; pass "
                "action_stats (mean/std from the raw action tensors) to the adapter."
            )

    @property
    def num_forward_calls(self) -> int:
        return self._calls

    def _normalize_blocks(self, blocks: torch.Tensor) -> torch.Tensor:
        """Normalize folded action blocks ``(..., frameskip * A)`` per raw dimension."""
        if not self.normalize or self.action_mean is None:
            return blocks
        mean = self.action_mean.repeat(self.frameskip)
        std = self.action_std.repeat(self.frameskip)
        return (blocks - mean) / std

    def _normalize_proprio(self, proprio: torch.Tensor) -> torch.Tensor:
        if not self.normalize or self.state_mean is None:
            return proprio
        dim = proprio.shape[-1]
        return (proprio - self.state_mean[:dim]) / self.state_std[:dim]

    def init_state(
        self,
        z_context: torch.Tensor,
        proprio_context: torch.Tensor | None = None,
        actions_context: torch.Tensor | None = None,
    ) -> dict[str, Any]:
        n = self.context_len
        z = z_context.float().to(self.device)
        if z.shape[0] < n:
            pad = z[:1].expand(n - z.shape[0], -1, -1)
            z = torch.cat([pad, z], dim=0)
        z = z[-n:]
        if proprio_context is None:
            proprio = torch.zeros(n, 1, device=self.device)
        else:
            proprio = proprio_context.float().to(self.device)
            if proprio.shape[0] < n:
                pad = proprio[:1].expand(n - proprio.shape[0], -1)
                proprio = torch.cat([pad, proprio], dim=0)
            proprio = self._normalize_proprio(proprio[-n:])
        block_dim = None
        if actions_context is not None and actions_context.shape[0] > 0:
            history = self._normalize_blocks(actions_context.float().to(self.device))
            block_dim = history.shape[-1]
        else:
            history = None
        if history is None or history.shape[0] < n - 1:
            if block_dim is None:
                if self.action_mean is None:
                    raise ValueError(
                        "actions_context is required to size the history action blocks "
                        "(or pass action_stats so zero-action padding can be built)."
                    )
                block_dim = self.action_mean.shape[0] * self.frameskip
            pad_raw = torch.zeros(
                (n - 1) - (0 if history is None else history.shape[0]),
                block_dim,
                device=self.device,
            )
            pad = self._normalize_blocks(pad_raw)
            history = pad if history is None else torch.cat([pad, history], dim=0)
        history = history[-(n - 1) :] if n > 1 else history[:0]
        return {
            "visual": z,
            "proprio": proprio,
            "history": history,  # already normalized
            "executed": history[:0],  # (0, block_dim), normalized space
            "current": z[-1],
        }

    def _extract_visual(self, result: Any) -> torch.Tensor:
        """Pull (B, T, P, D_visual) patch features out of an upstream rollout result."""
        value = result[0] if isinstance(result, tuple) else result
        if isinstance(value, dict):
            value = value.get("visual", next(iter(value.values())))
        if not torch.is_tensor(value):
            raise RuntimeError(f"Unexpected upstream rollout output type: {type(value)!r}")
        return value[..., : self.latent_dim]

    def _rollout(self, state: dict[str, Any], act: torch.Tensor) -> torch.Tensor:
        """Run upstream rollout for a (B, L, block_dim) normalized act tensor."""
        batch = act.shape[0]
        obs_0 = {
            "visual": state["visual"].unsqueeze(0).expand(batch, -1, -1, -1),
            "proprio": state["proprio"].unsqueeze(0).expand(batch, -1, -1),
        }
        self._calls += batch
        result = self.wm.rollout(obs_0=obs_0, act=act)
        return self._extract_visual(result)

    def rollout_final(self, state: dict[str, Any], actions: torch.Tensor) -> torch.Tensor:
        """Score candidates ``(B, K, fs*A)``: final latent after the K future steps.

        Processed in ``rollout_batch_size`` chunks; candidates are independent,
        so chunking changes memory use only, never the scores.
        """
        with torch.no_grad():
            candidates = self._normalize_blocks(actions.float().to(self.device))
            prefix = torch.cat([state["history"], state["executed"]], dim=0)
            finals = []
            for start in range(0, candidates.shape[0], self.rollout_batch_size):
                chunk = candidates[start : start + self.rollout_batch_size]
                act = torch.cat(
                    [prefix.unsqueeze(0).expand(chunk.shape[0], -1, -1), chunk], dim=1
                )
                visual = self._rollout(state, act)
                finals.append(visual[:, -1])
            return torch.cat(finals, dim=0)

    def advance(self, state: dict[str, Any], actions: torch.Tensor) -> dict[str, Any]:
        """Commit executed blocks ``(m, fs*A)``; replays from the original context."""
        with torch.no_grad():
            chunk = self._normalize_blocks(actions.float().to(self.device))
            executed = torch.cat([state["executed"], chunk], dim=0)
            act = torch.cat([state["history"], executed], dim=0).unsqueeze(0)
            visual = self._rollout(state, act)[0]
            m = chunk.shape[0]
            return {
                **state,
                "executed": executed,
                "current": visual[-1],
                "step_latents": visual[-m:],
            }

    def current_latent(self, state: dict[str, Any]) -> torch.Tensor:
        return state["current"]


def build_global_model(
    config: dict[str, Any],
    *,
    device: str = "cpu",
    action_stats: dict[str, np.ndarray] | None = None,
) -> Any:
    """Build the configured global model (synthetic or dino_wm)."""
    from wm_poc.dino_wm.configs import get_config_value
    from wm_poc.local_global.configs import action_data_dir

    source = str(get_config_value(config, "global_model.source", "dino_wm"))
    frameskip = int(get_config_value(config, "global_model.frameskip", 1))
    if source == "synthetic":
        return SyntheticPointGlobalModel(action_data_dir(config), frameskip=frameskip, device=device)
    if source == "dino_wm":
        ckpt_root = Path(str(get_config_value(config, "paths.global_ckpt_root"))).expanduser()
        model_name = get_config_value(config, "global_model.model_name")
        if not model_name:
            raise ValueError(
                "global_model.model_name is required for source=dino_wm "
                "(the upstream training run that produced the checkpoint)."
            )
        return DinoWMGlobalModel(
            Path(str(get_config_value(config, "paths.dino_wm_repo"))).expanduser(),
            ckpt_root / "outputs" / str(model_name),
            model_epoch=str(get_config_value(config, "global_model.model_epoch", "latest")),
            device=device,
            latent_dim=int(get_config_value(config, "global_model.latent_dim", 384)),
            frameskip=frameskip,
            num_hist=int(get_config_value(config, "global_model.num_hist", 3)),
            rollout_batch_size=int(
                get_config_value(config, "global_model.rollout_batch_size", 64)
            ),
            action_stats=action_stats,
        )
    raise ValueError(f"Unknown global_model.source: {source!r}")
